### ISSUE TITLE
Ajustes na segurança dos retornos negativos do backend 

### ISSUE THREAD

**Issue by zC4sTr0** [Rizzo-Dev-Ltda/raisetips-issues#55]
- Trocar o sistema para verificar se o status é 200 ao invés de verificar os "caminhos ruins" (como status 401, 403, etc)
- Trocar a função para boolean -> fazer com que a função seja suficiente por si só e não devolva um objeto de response: Função deve ser suficiente: IsAdmin -> True False = Mais fácil até de ler

Fazer semântica boa.

Avaliar middlewares com as mesmas lógicas.

**Comment by lkgiovani** [comment]
Avaliarei o back antes de fazer as mudanças.
